version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - MONGO_USER=jinali
      - MONGO_PASSWORD=jinali
    command: npm run dev
  mongo:
    ports:
      - 28017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jinali
      - MONGO_INITDB_ROOT_PASSWORD=jinali
      - MONGO_INITDB_DATABASE=post-app
