version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    command: node index.js
