version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jinali
      - MONGO_INITDB_ROOT_PASSWORD=jinali
      - MONGO_INITDB_DATABASE=post-app
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
